### ISSUE TITLE
How to pass in a dynamic context?

### ISSUE THREAD

**Issue by simonbuerger** [helpers/handlebars-helper-partial#5]
I'm trying to find a way to pass in the value of a variable as the context to a partial.

So given a data structure like this:

``` yaml
---
title: "Foo"
templateData: "templateQuestions"
```

I want to be able to pass `templateQuestions` in as the context object, where `templateQuestions` would be another yml file called templateQuestions.yml

Even vaguely possible? Any help figuring out how to write this would be greatly appreciated!
